services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: __xh8xq9KmE4E.CwpQDG
      MYSQL_DATABASE: Buddy2Go
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  server:
    image: buddy2go-server
    environment:
      DbSettings__Ip: mysql
      DbSettings__DbName: Buddy2Go
      DbSettings__UserID: root
      DbSettings__Password: __xh8xq9KmE4E.CwpQDG
      DbSettings__Port: 3306
      JwtSettings__Secret: "ThisIsASuperSecretKey12345678901"
      AllowedOrigins: "https://app.buddy-2-go.nl;https://app.buddy-2-go.nl:443;https://app.buddy-to-go.nl:5002;https://buddy2go-dev.nl;https://buddy2go-dev.nl:443;https://buddy2go-dev.nl:5002"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./certs/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy

  client:
    image: buddy2go-client
    volumes:
      - ./certs/client.crt:/etc/nginx/ssl/client.crt:ro
      - ./certs/client.key:/etc/nginx/ssl/client.key:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server

volumes:
  mysql_data: