apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buddy2go-ingress
  namespace: buddy2go
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - app.buddy-2-go.nl
      secretName: buddy2go-tls   # created by infra team
  rules:
    - host: app.buddy-2-go.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: buddy2go-client
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: buddy2go-server
                port:
                  number: 5001
