apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: buddy2go
data:
  DbSettings__Ip: "mysql"
  DbSettings__DbName: "Buddy2Go"
  DbSettings__UserID: "root"
  DbSettings__Password: "__xh8xq9KmE4E.CwpQDG"
  DbSettings__Port: "3306"

  JwtSettings__Secret: "ThisIsASuperSecretKey12345678901"

  AllowedOrigins: "https://app.buddy-2-go.nl;https://buddy2go-dev.nl;https://buddy2go-dev.nl:443"
