apiVersion: apps/v1
kind: Deployment
metadata:
  name: buddy2go-server
  namespace: buddy2go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buddy2go-server
  template:
    metadata:
      labels:
        app: buddy2go-server
    spec:
      containers:
        - name: server
          image: buddy2go-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: server-config
          ports:
            - containerPort: 5001
